### PR TITLE
customize dynamic-ws

### PR DESCRIPTION
**Pull request by zhang-rf**

### CODE REVIEW

**Comment by denosawr** [comment]
Current development is on the `store` branch instead of master; could you add these changes to the code there? It just makes things a little easier for us. Thanks!

**Comment by sylveon** [comment]
Hi!

Thanks for your contribution. However, he change you made has already
been added in the store branch. Additionally, the tint mode you
removed is still doable in said branch.

As the store branch is the branch we will use going forward, and for
the reason listed earlier, we won't merge this PR. Feel free to send
more pull requests targeting the store branch however!

-- 
Envoyé de mon Gmail

**Comment by zhang-rf** [comment]
If the change i made is already been added in the store branch, then when will the store branch be released? Thanks!

**Comment by sylveon** [comment]
@zhang-rf Progress on the store branch has been going well, and we're at the stage where only a few small features needs to be added. Plus, the school break coming next week, I'm confident we could get something stable during this period.

**Comment by zhang-rf** [comment]
@sylveon Good job. I'm looking forward to the next version!

**Pull request closed without merging**
