### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by maboroshin**
I have translated a variety of software.

I Diffed the English and Chinese files; other than the ```UniqueIdentifier```, the changes are the same as in that Diff. I simply created it in a text editor. So, there is no ```UniqueIdentifier``` in ```Xaml.vcxproj.filters```.

> The UniqueIdentifier node is optional.
https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-filters-files?view=msvc-170

And, I have tried to compile, but I am not using Windows 11. I can't even try SDK build 22543. Visual Studio said you need SDK build 22543.

### CODE REVIEW

**Review by sylveon — APPROVED** [review]

**Comment by sylveon** [comment]
Thanks for the contribution! I really appreciate it.

**Comment by sylveon** [comment]
Hello! I'm in the process of releasing the new update, and can't submit the update until I fill out the Japanese store listing as well:
image

Would you be able to fill out the Japanese column of this CSV? This would help me greatly!
[store-listing.csv](https://github.com/TranslucentTB/TranslucentTB/files/10100986/store-listing.csv)

Thank you!

**Comment by maboroshin** [comment]
@sylveon I have completed. Congratulations on the award!
[store-listing.csv](https://github.com/TranslucentTB/TranslucentTB/files/10101969/store-listing.csv)

**Comment by sylveon** [comment]
Thank you so much for this! (and thank you for the congratulations as well)

**Pull request merged**
