### PR TITLE
Optimize zh-cn translation in store-listing.csv

### PR DESCRIPTION
**Pull request by EightEggs**

### CODE REVIEW

**Comment by EightEggs** [comment]
Oh, it seems that I should have made this pr to `develop` branch.
Sorry for the inconvenience.(qwq)

**Comment by sylveon** [comment]
No worries, I'll fix the conflicts

**Review by sylveon — APPROVED** [review]
Thanks for the contribution!

**Comment by EightEggs** [comment]
> Thanks for the contribution!

Thanks for your work on the awesome App! :)

**Pull request merged**
