### PR TITLE
Note compatibility with ExplorerPatcher

### PR DESCRIPTION
**Pull request by TheGamer1002**
This shouldn't be anything breaking, just changing the readme.

### CODE REVIEW

**Comment by sylveon** [comment]
While compatibility with ExplorerPatcher is definitely a nice thing worth mentionning, I don't think it should displayed as almost the first thing in the readme. Maybe move it to a bullet point in "Features" instead? Also, it would be nice to make the "ExplorerPatcher" mention clickable and direct to their GitHhub page.

**Comment by TheGamer1002** [comment]
Alright, will get on that now.

**Comment by TheGamer1002** [comment]
Done! I will make a PR on EP's readme.

**Comment by TheGamer1002** [comment]
That is now done.

**Review by sylveon — APPROVED** [review]

**Pull request merged**
