### PR TITLE
Italian Translation 

### PR DESCRIPTION
**Pull request by TheBossMagnus**
image
Having some issues compiling(probably related to .rc2)

### CODE REVIEW

**Comment by sylveon** [comment]
You have to set the AppPackage project as the startup project (in the solution explorer, right click AppPackage and click set as startup project)

**Comment by sylveon** [comment]
Also please add Italians strings to store-listing.csv

**Review by sylveon — CHANGES_REQUESTED** [review]
I have noticed untranslated strings. is this intentional?
- TranslucentTB Open Source Developers (in AppPackage, TranslucentTB and store-listing.csv)
- Copyright ©️ 2022 Open Source Developers (in TranslucentTB and store-listing.csv)
- Photo by X on Unsplash (in store-listing.csv)
- Release notes in store-listing.csv
- taskbar and fluent keywords in store-listing.csv
- Debug 
- Blur
- Desktop

Unsure if the last 4 are simply the same in Italian, however. Please pull changes before fixing this, I fixed merge conflicts and corrected a few things

**Comment by TheBossMagnus** [comment]
TranslucentTB Open Source Developers (in AppPackage, TranslucentTB and store-listing.csv) = Is "TranslucentTB Open Source Developers" a organization name?
Copyright ©️ 2022 Open Source Developers (in TranslucentTB and store-listing.csv)
Photo by X on Unsplash (in store-listing.csv) = my bad
Release notes in store-listing.csv = my bad v2
taskbar and fluent keywords in store-listing.csv = my badv3
Debug = no existing Italian word
Blur = no existing Italian word
Desktop = no existing Italian word

**Comment by sylveon** [comment]
> Is "TranslucentTB Open Source Developers" a organization name?

No, it refers to the developers who contributed to TranslucentTB, so you would translate the whole thing except "TranslucentTB"

**Comment by sylveon** [comment]
Closing as no author reply

**Pull request closed without merging**
