### PR TITLE
feat: Internationalization

### PR DESCRIPTION
**Pull request by Thor-x86**
Strings are now no longer hardcoded. Thus, anyone can translate without requiring deep dive into the source code. Just follow the TRANSLATOR_GUIDE.md

### CODE REVIEW

**Comment by sylveon** [comment]
From a cursory glance, everything looks fine! I'll take a better look at it when I have time.

**Comment by Thor-x86** [comment]
A question for signing commit: I did sign it with PGP key, now what should I do in order to allow the test running? Thanks!

**Comment by sylveon** [comment]
The CI hasn't passed for a while now, we use the 22000 SDK for some important bug fixes and the worker images don't have it installed yet.

**Comment by wertone-gh** [comment]
I can make polish translation once this is merged.

**Review by sylveon — APPROVED** [review]

**Comment by maboroshin** [comment]
I have been waiting for this.

＠Thor-x86
> Just follow the TRANSLATOR_GUIDE.md

Is this means [Thor-x86/TranslucentTB/CONTRIBUTING.md](https://github.com/Thor-x86/TranslucentTB/blob/4174de578802b0aa9aa5708c4000ff55897566a2/CONTRIBUTING.md#translating-translucenttb) ?

**Pull request merged**
