### PR TITLE
Indonesian Translation

### PR DESCRIPTION
**Pull request by Anfia**
Heya, it's me, Anfia from your Translucent TB discord server.
Here's for the Indonesian Translation that I submit for your TranslucentTB app.

It's all work really well with your guidance.
For store-listing.csv, I think you should look it first before continue, since I'm edit it using Excel 2016, but legacy one (the one that still flat logo a.k.a. msi installer version).

Thank you (><)

### CODE REVIEW

**Comment by sylveon** [comment]
Everything looks good, except it looks like you exported the CSV to be using semi-colons as delimiters. They need to be using commas. Can you correct this?

**Comment by Anfia** [comment]
All right, I fix it to using commas. Checking by Notepad++, it's clear.
It should be ready to full merge. :)

https://github.com/TranslucentTB/TranslucentTB/pull/809/commits/25bd66181e62168fd2e0418c14fdaa9a29a29557

**Comment by Anfia** [comment]
Hold up, the csv is already in commas, but the non-alpahebt word become ???? instead their characters.
Let me re-check again

**Comment by Anfia** [comment]
All right, this should be ready to go full merge. ;)

https://github.com/TranslucentTB/TranslucentTB/pull/809/commits/04326795bd7ec521704465b1c592d3a6249955cb

[store-listing.csv](https://github.com/TranslucentTB/TranslucentTB/files/11111971/store-listing.csv)

**Review by sylveon — APPROVED** [review]
Looks perfect now, thank you for the contribution!

**Pull request merged**
