### PR TITLE
Multi-language localization support

### PR DESCRIPTION
**Pull request by Simakeng**
Added localization loader, can easily provide localization support for any language (now supports Chinese and English).And modifying the displayed text is now easier.
IV_9FHYW``_UJ$O@@P(944R

### CODE REVIEW

**Comment by Simakeng** [comment]
Is this a problem with Appveyor? I can build this "StorePacakage" on my computer.
`error APPX0108: The certificate specified has expired. For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478. [C:\projects\translucenttb\StorePackage\StorePackage.wapproj]`

**Comment by sylveon** [comment]
AppVeyor build has been broken for a while, you can ignore it.

**Comment by Simakeng** [comment]
Why hasn't this branch been merged?

**Comment by sylveon** [comment]
Because the dev branch already has basic localization support using another technique, has more things to translate (XAML for example), as well as not being fully final yet so efforts translating it would probably have to be redone for release.

If I where to merge this, I'll just end up having to override all of it.

**Pull request closed without merging**
