### PR TITLE
Added AutoStartUp

### PR DESCRIPTION
**Pull request by ghost1372**
Added AutoStartUp
Added Version Info
Changed Default from Blur to Clear

### CODE REVIEW

**Comment by ethanhs** [comment]
Hi, thanks so much for this. It looks like you used a newer version of visual studio  (looks like vs 2017). We try to use 2015 because not everyone is using the later IDE, and the project files are not backwards compatible. Also, my laptops wifi isnt working, but Id like to test and review this more thoroughly once it is.

**Comment by charlesmilette** [comment]
I'm currently rewriting the commit to remove the VS-2017 specific parts

**Comment by ethanhs** [comment]
I'm going to go ahead and fix things. I do want to keep the taskbar blurred as default. I am ok with automatically installing the startup location. If we need, I can add a .reg file to uninstall the autostart, it should be pretty easy. I will review this in a bit.

**Comment by olliethepikachu** [comment]
Thanks so much for this! I've changed it slightly so you have to call `TranslucentTB --startup` to add it to startup; this was done pretty quick and rushed, so I've only had time to copy and paste code and to build and test it. Tomorrow I'll try to take a look into allowing for uninstall through command line, and possibly another idea I'm thinking about (relating to this).

**Comment by olliethepikachu** [comment]
Explanation for my changes: many people download applications like this from third-party websites and don't get to read the fine print. If someone doesn't like TTB, to remove it would be a pain as they wouldn't be able to remove it (don't forget that most people lack basic computer literacy skills :D)

**Comment by charlesmilette** [comment]
I'm working on a basic context menu entry, should check in a couple of minutes.

**Comment by charlesmilette** [comment]
Seems to be working for me now.

**Comment by ethanhs** [comment]
This is great _except_ that it isn't targeting `develop`, the branch PRs are supposed to be made against. There are now some merge conflicts. @ghost1372 can you rebase against `develop` for your changes?

**Comment by ghost1372** [comment]
@ethanhs  I am a new at GitHub.
If you guide me, maybe I can. i use visual studio with github extension for pushing commits.

**Comment by charlesmilette** [comment]
I could always try merging this manually and fixing the conflicts

**Comment by ethanhs** [comment]
Okay, that works too. Thanks @charlesmilette. I am going to add my change to get dynamic-start working and then we can merge that into develop.

**Pull request merged**
