### PR TITLE
Improve Chinese Translation

### PR DESCRIPTION
**Pull request by littlewhitecloud**
improve something sounds strange

### CODE REVIEW

**Comment by littlewhitecloud** [comment]
I think it is finished. Is there any maintainer to check it out?

**Comment by littlewhitecloud** [comment]
I think it is finished... Any maintainers can check it out?

**Comment by littlewhitecloud** [comment]
@sylveon could you check this pr out?

**Comment by Tesutarin** [comment]
#725 已经优化并完善了翻译，因此不需要再更新翻译了

**Comment by sylveon** [comment]
This seems to have some additional improvements that your PR doesn't have. However, it seems the flow of text in the welcome page was changed. Is that normal?

**Comment by littlewhitecloud** [comment]
What does the "flow of text in the welcome page" mean?

**Comment by sylveon** [comment]
It ends the sentence in the prefix, then starts a new one in the hyperlink, which is not what the original English text is like. A foolish translation on Google Translate seems to confirm this.
New:
image

Old:
image

**Comment by littlewhitecloud** [comment]
So should I use the old translation?

**Comment by littlewhitecloud** [comment]
image
What about now?

**Comment by sylveon** [comment]
Yeah, this sounds better

**Comment by littlewhitecloud** [comment]
Sylveon, May I ask you a question?

**Comment by sylveon** [comment]
Yes

**Comment by littlewhitecloud** [comment]
How translucenttb works?
I wonder if it works the same way I thought.

**Comment by sylveon** [comment]
Calls SetWindowCompositionAttribute on the taskbar's window (but with a lot of extra bells and whistles)

**Comment by littlewhitecloud** [comment]
Okay, thanks. Because I want to figure out why translucenttb doesn't work on Windows 11 22621.1343. (If the hwnd of the taskbar is right and also windows 11 have the right blur, why it doesn't work)

**Comment by littlewhitecloud** [comment]
Is there still anything wrong in this pr? (I'll be able to fix it right away)

**Comment by sylveon** [comment]
Nothing so far, I'll take a closer look sometime this week.

**Comment by sylveon** [comment]
Thanks for the contribution!

**Comment by littlewhitecloud** [comment]
Thank you too! You are a great developer!

**Pull request merged**
